vich_uploader:
    db_driver: orm

    mappings:
       customuploadedfiles:
           uri_prefix: /uploadedfiles
           upload_destination: '%kernel.project_dir%/public/files'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
